<html doctype>
	<head title="CfPBoK for SLE 2014 SI" />
	<body>
		<credit project="CfPBoK@https://slebok.github.io/cfpbok/"/>
		<div class="right"><img src="../sle.png" alt="SLE 2014 SI logo"></div>
			<h1><a href="../sle2014/index.html">SLE 2014</a> SI</h1>
			<ul>
				<li><a href="#cfp">Call for Papers</a></li>
				<li><a href="#lop">List of Papers</a></li>
				<li><a href="#org">Organisers</a></li>
				<li>Tags requested: <ul><li><a href="../tag/t1c.html"><span class="tagM" title="T1C: Behavioural Semantics">T1C</span></a> <a href="../tag/t2a.html"><span class="tagM" title="T2A: Lifecycle">T2A</span></a> <a href="../tag/t2b.html"><span class="tagM" title="T2B: Evolution">T2B</span></a> <a href="../tag/t2d.html"><span class="tagM" title="T2D: Deployment">T2D</span></a> <a href="../tag/t3c.html"><span class="tagM" title="T3C: DSLs">T3C</span></a> <a href="../tag/t3d.html"><span class="tagM" title="T3D: GPLs">T3D</span></a> <a href="../tag/t3e.html"><span class="tagM" title="T3E: Ontologies">T3E</span></a> <a href="../tag/t4a.html"><span class="tagM" title="T4A: Workbenches">T4A</span></a> <a href="../tag/t4b.html"><span class="tagM" title="T4B: Horizontal Transformation">T4B</span></a> <a href="../tag/t4d.html"><span class="tagM" title="T4D: Interpretation">T4D</span></a> <a href="../tag/t4e.html"><span class="tagM" title="T4E: Simulation">T4E</span></a> <a href="../tag/t5b.html"><span class="tagM" title="T5B: Language Description Analysis">T5B</span></a> <a href="../tag/t5c.html"><span class="tagM" title="T5C: Testing">T5C</span></a> <a href="../tag/t5d.html"><span class="tagM" title="T5D: Formal Methods">T5D</span></a> <a href="../tag/t5e.html"><span class="tagM" title="T5E: Empirical Evaluation">T5E</span></a> <a href="../tag/t5f.html"><span class="tagM" title="T5F: Performance">T5F</span></a> <a href="../tag/t5h.html"><span class="tagM" title="T5H: Usability">T5H</span></a> <a href="../tag/t6a.html"><span class="tagM" title="T6A: Experience Reports">T6A</span></a> <a href="../tag/t6d.html"><span class="tagM" title="T6D: Synergies">T6D</span></a> </li></ul></li>
<li>Tags received: <ul><li><a href="../tag/t1c.html"><span class="tagL" title="T1C: Behavioural Semantics">T1C</span></a> <a href="../tag/t1d.html"><span class="tagL" title="T1D: Composition">T1D</span></a> <a href="../tag/t1e.html"><span class="tagL" title="T1E: Reuse">T1E</span></a> <a href="../tag/t3a.html"><span class="tagM" title="T3A: Meta-languages">T3A</span></a> <a href="../tag/t3b.html"><span class="tagL" title="T3B: Transformation Languages">T3B</span></a> <a href="../tag/t3c.html"><span class="tagL" title="T3C: DSLs">T3C</span></a> <a href="../tag/t4a.html"><span class="tagM" title="T4A: Workbenches">T4A</span></a> <a href="../tag/t4c.html"><span class="tagM" title="T4C: Vertical Transformation">T4C</span></a> <a href="../tag/t4d.html"><span class="tagL" title="T4D: Interpretation">T4D</span></a> <a href="../tag/t5b.html"><span class="tagL" title="T5B: Language Description Analysis">T5B</span></a> <a href="../tag/t5d.html"><span class="tagM" title="T5D: Formal Methods">T5D</span></a> <a href="../tag/t5e.html"><span class="tagL" title="T5E: Empirical Evaluation">T5E</span></a> <a href="../tag/t5f.html"><span class="tagL" title="T5F: Performance">T5F</span></a> <a href="../tag/t5h.html"><span class="tagL" title="T5H: Usability">T5H</span></a> <a href="../tag/t6d.html"><span class="tagL" title="T6D: Synergies">T6D</span></a> </li></ul></li>
			</ul>
<h2 id="cfp">Call for Papers (<a href="https://doi.org/10.1016/j.cl.2015.08.009">source</a>)</h2>
<p>
</p>
<p>Software Language Engineering (SLE) is the application of systematic, disciplined, and measurable approaches to the <span class="term">development</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span>, use, <span class="term">deployment</span><span class="tag" title="T2D: Deployment"><a href="../tag/t2d.html">T2D</a></span>, and <span class="term">maintenance</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span> of software languages. The term “software language” is used broadly, and includes: <span class="term">general-purpose programming languages</span><span class="tag" title="T3D: GPLs"><a href="../tag/t3d.html">T3D</a></span>; <span class="term">domain-specific languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span> (e.g. BPMN, <span class="term">Simulink</span><span class="tag" title="T4E: Simulation"><a href="../tag/t4e.html">T4E</a></span>, Modelica, SQL, Yacc); modeling and metamodeling languages (e.g. SysML and UML); data models and <span class="term">ontologies</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span> (e.g. XML-based and OWL-based languages and vocabularies).
</p>
<p>
</p>
<p>The SLE conference series (<a href="http://www.sleconf.org">http://www.sleconf.org</a>) is devoted to a wide range of topics related primarily to the use of computer languages in Software Engineering. <span class="term">SLE brings together several communities that have traditionally looked at software languages from different and yet complementary perspectives</span><span class="tag" title="T6D: Synergies"><a href="../tag/t6d.html">T6D</a></span>: programming languages, model driven engineering, domain specific languages, and semantic web. Furthermore, SLE crosses a number of different technological spaces, including: context-free grammars, object-oriented modeling frameworks, rich data, structured data, object-oriented programming, functional programming, logic programming, <span class="term">term-rewriting</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, attribute grammars, <span class="term">algebraic specification</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span>, etc. Supporting these communities in <span class="term">learning from each other</span><span class="tag" title="T6D: Synergies"><a href="../tag/t6d.html">T6D</a></span>, and transferring knowledge is the guiding principle behind the organisation of SLE.
</p>
<p>
</p>
<p>This special issue of the Computer Languages, Systems & Structures journal (COMLAN) includes extended and revised versions of selected papers from the programs of <a href="../sle2013/index.html">SLE 2013</a> and <a href="../sle2014/index.html">SLE 2014</a>.
</p>
<p>
</p>
<p>The 6th International Conference on Software Language Engineering (<a href="../sle2013/index.html">SLE 2013</a>) was held on October 27th and 28th, 2013, co-located with SPLASH and OOPSLA in Indianapolis, USA. Fifty Six papers were originally submitted to <a href="../sle2013/index.html">SLE 2013</a>, and from these submissions the Program Committee selected 17 papers and two tools papers [2]. Each submitted paper was reviewed by at least three PC members, and was discussed in detail. Careful consideration in terms of a balanced program was given, so that representative state-of-the-art research from different approaches to software language engineering appeared on the program.
</p>
<p>
</p>
<p>The 7th International Conference on Software Language Engineering (<a href="../sle2014/index.html">SLE 2014</a>) was held on September 15th and 16th 2014, co-located with ASE and GPCE in Västerås, Sweden. 64 papers were originally submitted to <a href="../sle2014/index.html">SLE 2014</a>. From these submissions, the Program Committee (PC) eventually selected 19 papers [1] 16 out of 53 research papers (for an acceptance rate of 30%), and 3 out of 8 tool papers (for an acceptance rate of 37%). Each submitted paper was reviewed by at least three PC members and discussed in detailed during the electronic discussion period. Awards were given out as part of the program for the overall best paper, the overall best student paper and the best reviewer.
</p>
<p>
</p>
<p>The editors of this special issue are the PC chairs of SLE 2013[/] and [r]SLE 2014. They selected outstanding papers from the two programs of the SLE conference, and invited the authors to submit a revised and extended version of their papers. All papers have been carefully reviewed by at least three reviewers, and followed the strict review process of the journal until the final decision of each paper was reached.
</p>
<p>The authors of three papers from <a href="../sle2013/index.html">SLE 2013</a> were invited to submit extended versions of their papers. These received three reviews in each iteration of the review process and were accepted for inclusion. These papers are
</p>
<p>
</p>
<ul>
<li>Declarative Rewriting Through Circular Nonterminal Attributes by Emma Söderberg and Görel Hedin which unifies two modern extensions to attribute grammars, rewriting and circular attributes, both which add a different fixed point computation to attribute grammars. The resulting unification incorporates both extensions as a new fixed point computation over higher order attributes.</li>
<li><span class="term">Evaluating and Comparing</span><span class="tag" title="T5E: Empirical Evaluation"><a href="../tag/t5e.html">T5E</a></span> <span class="term">Language Workbenches</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span>: <span class="term">Existing Results</span><span class="tag" title="T6A: Experience Reports"><a href="../tag/t6a.html">T6A</a></span> and Benchmarks for the Future, by Sebastian Erdweg, Tijs van der Storm, Markus Völter, Meinte Boersma, Remi Bosman, William R. Cook, Albert Gerritsen, Angelo Hulshout, Steven Kelly, Alex Loh, Gabriël Konat, Pedro J. Molina, Martin Palatnik, Eugen Schindler, Klemens Schindler, Riccardo Solmi, Vlad Vergu, Eelco Visser, Kevin van der Vlist, Guido Wachsmuth and Jimi van der Woning. This paper, by the leading experts, developers and maintainers of language workbenches, presents an analysis of the state of the art in language workbenches, as well as a set of benchmark problems that can help drive and challenge future development and improvement.</li>
<li>Symbolic execution based on <span class="term">language transformation</span><span class="tag" title="T5B: Language Description Analysis"><a href="../tag/t5b.html">T5B</a></span> by Andrei Arusoaie, Dorel Lucanu and Vlad Rusu. This paper presents a detailed and rigorous language-independent symbolic execution framework for languages endowed with a formal <span class="term">operational semantics</span><span class="tag" title="T1C: Behavioural Semantics"><a href="../tag/t1c.html">T1C</a></span> based on term rewriting. The approach presented in this paper is novel: starting from a language definition, a <span class="term">new is generated</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span> with the same syntax as the original, but whose semantical rules are transformed in order to rewrite over logical formulas denoting possibly infinite sets of program states. The symbolic execution of concrete programs is, by definition, the execution of the same programs but with the symbolic semantics.</li>
</ul>
<p>
</p>
<p>The editors of this special issue selected 4 papers out of the 19 papers accepted at <a href="../sle2014/index.html">SLE 2014</a>, and 3 papers were eventually accepted for inclusion in the special issue
</p>
<p>
</p>
<ul>
<li>Intra- and Interdiagram Consistency Checking of Behavioral Multiview Models by Petra Kaufmann, Martin Kronegger, Andreas Pfandler, Martina Seidl, Magdalena Widl. This paper introduces a novel approach based on <span class="term">SAT solving</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span> to check crosscutting constraints in the context of multi-view modeling. Authors experimentally <span class="term">evaluate</span><span class="tag" title="T5E: Empirical Evaluation"><a href="../tag/t5e.html">T5E</a></span> the <span class="term">scalability</span><span class="tag" title="T5F: Performance"><a href="../tag/t5f.html">T5F</a></span> of the solution and show convincing results.</li>
<li>Practical domain-specific <span class="term">debuggers</span><span class="tag" title="T5C: Testing"><a href="../tag/t5c.html">T5C</a></span> using the Moldable Debugger framework by Andrei Chiş, Marcus Denker, Tudor Gîrba, Oscar Nierstrasz. In this paper, the authors introduce the Moldable Debugger, a framework for developing domain-specific debuggers. The <span class="term">framework</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span> supports the definition of domain-specific operations and views that can be <span class="term">selected at runtime</span><span class="tag" title="T4D: Interpretation"><a href="../tag/t4d.html">T4D</a></span> to help developers reason about and formulate domain-specific questions using concepts and abstractions from their application domains. The authors also provide a convincing <span class="term">evaluation</span><span class="tag" title="T5E: Empirical Evaluation"><a href="../tag/t5e.html">T5E</a></span> of the Moldable Debugger from both a <span class="term">performance</span><span class="tag" title="T5F: Performance"><a href="../tag/t5f.html">T5F</a></span> and <span class="term">usability</span><span class="tag" title="T5H: Usability"><a href="../tag/t5h.html">T5H</a></span> point of view.</li>
<li>Bounded Seas by Jan Kurš, Mircea Lungu, Rathesan Iyadurai, Oscar Nierstrasz. This paper presents a new way of thinking about “Island Grammars”, which have been used previously for parsing input with incomplete knowledge. Island grammars target particular subsets (the islands) of some grammar whilst ignoring the remaining unrecognised input (the water). Traditional approaches have assumed that water should consume everything until an island is detected, but this can lead to problems. The approach taken in this paper is to define specialised water for each island, depending on its context.</li>
</ul>
<p>
</p>
<p>As editors of this special issue, we hope you will enjoy this selection of insightful papers and will appreciate the diversity of topics currently investigated in the field of Software Language Engineering.
</p>
<p>We would like to thank the many people who have contributed to the success of <a href="../sle2013/index.html">SLE’13</a> and <a href="../sle2014/index.html">SLE’14</a> and, subsequently, this special issue. In particular, the general chairs for <a href="../sle2013/index.html">SLE’13</a> and <a href="../sle2014/index.html">SLE’14</a> (respectively Eric Van Wyk and Jurgen Vinju), the Programme Committee and Steering Committee members of both conferences and the numerous external reviewers who contributed to the important task of reviewing papers for both conferences and/or this special issue. We would also particularly like to thank COMLAN’s Editor-in-Chief, Marjan Mernik, for all the help he provided along the way.
</p><h2 id="lop">List of Papers (<a href="https://dblp.org/db/journals/cl/cl44.html#journals/cl/CombemalePPW15">source</a>)</h2>
<ul class="lop">

<li><em><a href="paper01.html">Declarative rewriting through circular nonterminal attributes</a></em> (<a href="../profile/EmmaSöderberg.html">Emma Söderberg</a>, <a href="../profile/GörelHedin.html">Görel Hedin</a>)
<ul><li>
<a href="../tag/t3a.html"><span class="tagM" title="The paper advances the meta-language of reference attribute grammars (RAGs), introducing circular nonterminal attributes and an evaluation algorithm.">T3A: Meta-languages</span></a>
<a href="../tag/t3b.html"><span class="tagL" title="Rewriting/AST transformation is a first-class concern, and the paper shows equivalence/mappings between rewrites and circular NTAs.">T3B: Transformation Languages</span></a>
<a href="../tag/t1c.html"><span class="tagL" title="The contribution is centered on executable semantics mechanisms (demand-driven evaluation, fixed-point iteration) for language definitions.">T1C: Behavioural Semantics</span></a>
<a href="../tag/t5e.html"><span class="tagL" title="It includes an experimental evaluation comparing algorithms on implemented example languages.">T5E: Empirical Evaluation</span></a>
</li></ul></li>
<li><em><a href="paper02.html">Evaluating and comparing language workbenches: Existing results and benchmarks for the future</a></em> (<a href="../profile/SebastianErdweg.html">Sebastian Erdweg</a>, <a href="../profile/TijsvanderStorm.html">Tijs van der Storm</a>, <a href="../profile/MarkusVölter.html">Markus Völter</a>, <a href="../profile/LaurenceTratt.html">Laurence Tratt</a>, <a href="../profile/RemiBosman.html">Remi Bosman</a>, <a href="../profile/WilliamRCook.html">William R. Cook</a>, <a href="../profile/AlbertGerritsen.html">Albert Gerritsen</a>, <a href="../profile/AngeloHulshout.html">Angelo Hulshout</a>, <a href="../profile/StevenKelly.html">Steven Kelly</a>, <a href="../profile/AlexLoh.html">Alex Loh</a>, <a href="../profile/GabriëlKonat.html">Gabriël Konat</a>, <a href="../profile/PedroJMolina.html">Pedro J. Molina</a>, <a href="../profile/MartinPalatnik.html">Martin Palatnik</a>, <a href="../profile/RistoPohjonen.html">Risto Pohjonen</a>, <a href="../profile/EugenSchindler.html">Eugen Schindler</a>, <a href="../profile/KlemensSchindler.html">Klemens Schindler</a>, <a href="../profile/RiccardoSolmi.html">Riccardo Solmi</a>, <a href="../profile/VladVergu.html">Vlad Vergu</a>, <a href="../profile/EelcoVisser.html">Eelco Visser</a>, <a href="../profile/KevinvanderVlist.html">Kevin van der Vlist</a>, <a href="../profile/GuidoWachsmuth.html">Guido Wachsmuth</a>, <a href="../profile/JimivanderWoning.html">Jimi van der Woning</a>)
<ul><li>
<a href="../tag/t4a.html"><span class="tagM" title="The paper’s main subject is language workbenches and their associated tooling ecosystems.">T4A: Workbenches</span></a>
<a href="../tag/t5e.html"><span class="tagL" title="It reports comparative/empirical evidence (Language Workbench Challenge results) and distills benchmark data and observations.">T5E: Empirical Evaluation</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="Workbenches are evaluated specifically as platforms for building and using DSLs.">T3C: DSLs</span></a>
<a href="../tag/t6d.html"><span class="tagL" title="It aligns perspectives across multiple tools/communities by proposing shared benchmarks and a common feature model.">T6D: Synergies</span></a>
</li></ul></li>
<li><em><a href="paper03.html">Symbolic execution based on language transformation</a></em> (<a href="../profile/AndreiArusoaie.html">Andrei Arusoaie</a>, <a href="../profile/DorelLucanu.html">Dorel Lucanu</a>, <a href="../profile/VladRusu.html">Vlad Rusu</a>)
<ul><li>
<a href="../tag/t4c.html"><span class="tagM" title="Starting from a formal operational semantics, the paper automatically generates a transformed “symbolic” language definition enabling symbolic execution.">T4C: Vertical Transformation</span></a>
<a href="../tag/t1c.html"><span class="tagL" title="The technique is semantics-driven: it relies on executable operational semantics (term rewriting) as the basis for execution/analysis.">T1C: Behavioural Semantics</span></a>
<a href="../tag/t5d.html"><span class="tagL" title="Symbolic execution, reachability analysis, and model checking are core formal-methods goals and evaluation targets.">T5D: Formal Methods</span></a>
<a href="../tag/t4a.html"><span class="tagL" title="A prototype is implemented inside the K framework’s compilation pipeline, i.e., as language-engineering tooling.">T4A: Workbenches</span></a>
</li></ul></li>
<li><em><a href="paper04.html">Intra- and interdiagram consistency checking of behavioral multiview models</a></em> (<a href="../profile/PetraRadeljakKaufmann.html">Petra Radeljak Kaufmann</a>, <a href="../profile/MartinKronegger.html">Martin Kronegger</a>, <a href="../profile/AndreasPfandler.html">Andreas Pfandler</a>, <a href="../profile/MartinaSeidl.html">Martina Seidl</a>, <a href="../profile/MagdalenaWidl.html">Magdalena Widl</a>)
<ul><li>
<a href="../tag/t5d.html"><span class="tagM" title="The contribution is a formal consistency-checking method for behavioral models (with SAT solving as the underlying decision procedure).">T5D: Formal Methods</span></a>
<a href="../tag/t5b.html"><span class="tagL" title="It analyses language artifacts (behavioral UML models/diagrams) to detect and explain inconsistencies across views.">T5B: Language Description Analysis</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="The work targets a domain/purpose-specific modeling setting (behavioral multiview models) rather than general-purpose programming.">T3C: DSLs</span></a>
</li></ul></li>
<li><em><a href="paper05.html">Practical domain-specific debuggers using the Moldable Debugger framework</a></em> (<a href="../profile/AndreiChiș.html">Andrei Chiș</a>, <a href="../profile/MarcusDenker.html">Marcus Denker</a>, <a href="../profile/TudorGîrba.html">Tudor Gîrba</a>, <a href="../profile/OscarNierstrasz.html">Oscar Nierstrasz</a>)
<ul><li>
<a href="../tag/t4a.html"><span class="tagM" title="The central contribution is a framework (tooling/workbench support) for constructing domain-specific debuggers via reusable operations and views.">T4A: Workbenches</span></a>
<a href="../tag/t4d.html"><span class="tagL" title="The work is about inspecting and interacting with running program executions (debugging runtime behavior).">T4D: Interpretation</span></a>
<a href="../tag/t5h.html"><span class="tagL" title="A primary motivation is improving developer workflow and reducing the abstraction gap/cognitive load through tailored debugging views.">T5H: Usability</span></a>
<a href="../tag/t5f.html"><span class="tagL" title="The paper discusses implementation strategies and their performance impact (notably overhead being opt-in).">T5F: Performance</span></a>
</li></ul></li>
<li><em><a href="paper06.html">Bounded seas</a></em> (<a href="../profile/JanKurš.html">Jan Kurš</a>, <a href="../profile/MirceaLungu.html">Mircea Lungu</a>, <a href="../profile/RathesanIyadurai.html">Rathesan Iyadurai</a>, <a href="../profile/OscarNierstrasz.html">Oscar Nierstrasz</a>)
<ul><li>
<a href="../tag/t3a.html"><span class="tagM" title="The paper proposes a grammar-based technique (“bounded seas”) for island parsing/semi-parsing, i.e., engineering and composing grammar descriptions.">T3A: Meta-languages</span></a>
<a href="../tag/t1d.html"><span class="tagL" title="The key technical goal is composability of islands and their surrounding “water”, which is a modularity/composition concern in language definitions.">T1D: Composition</span></a>
<a href="../tag/t1e.html"><span class="tagL" title="The technique is motivated by making islands reusable across contexts by generating island-specific “water” automatically.">T1E: Reuse</span></a>
<a href="../tag/t4a.html"><span class="tagL" title="The approach is presented with tool support by integrating bounded seas into a parser combinator framework.">T4A: Workbenches</span></a>
</li></ul></li></ul><h2 id="org">Organisers</h2><ul><li><a href="../profile/BenoîtCombemale.html">Benoît Combemale</a> (<a href="https://doi.org/10.1016/j.cl.2015.08.009">Editor</a>)</li><li><a href="../profile/DavidJPearce.html">David J. Pearce</a> (<a href="https://doi.org/10.1016/j.cl.2015.08.009">Editor</a>)</li><li><a href="../profile/RichardFPaige.html">Richard F. Paige</a> (<a href="https://doi.org/10.1016/j.cl.2015.08.009">Editor</a>)</li><li><a href="../profile/EricVanWyk.html">Eric Van Wyk</a> (<a href="https://doi.org/10.1016/j.cl.2015.08.009">Editor</a>)</li></ul>
		<clear/>
		<footer/>
	</body>
</html>
