<html doctype>
	<head title="CfPBoK for SLE 2013" />
	<body>
		<credit project="CfPBoK@https://slebok.github.io/cfpbok/"/>
		<div class="right"><a href="../index.html"><img src="../sle.png" alt="SLE 2013 logo"></a></div>
			<h1>SLE 2013</h1>
			<ul>
              <li>Co-located with SPLASH (GPCE et al)</li>
              <li><a href="https://www.sleconf.org/2013/">Conference website</a></li>
				<li><a href="#cfp">Call for Papers</a></li>
				<li><a href="#lop">List of Papers</a></li>
				<li><a href="#org">Organisers</a></li>
				<li>Tags requested: <ul><li><a href="../tag/t1a.html"><span class="tagM" title="T1A: Design">T1A</span></a> <a href="../tag/t1b.html"><span class="tagM" title="T1B: Static Semantics">T1B</span></a> <a href="../tag/t1d.html"><span class="tagM" title="T1D: Composition">T1D</span></a> <a href="../tag/t2a.html"><span class="tagM" title="T2A: Lifecycle">T2A</span></a> <a href="../tag/t2b.html"><span class="tagM" title="T2B: Evolution">T2B</span></a> <a href="../tag/t2d.html"><span class="tagM" title="T2D: Deployment">T2D</span></a> <a href="../tag/t2e.html"><span class="tagM" title="T2E: Documentation">T2E</span></a> <a href="../tag/t3a.html"><span class="tagM" title="T3A: Meta-languages">T3A</span></a> <a href="../tag/t3b.html"><span class="tagM" title="T3B: Transformation Languages">T3B</span></a> <a href="../tag/t3c.html"><span class="tagM" title="T3C: DSLs">T3C</span></a> <a href="../tag/t3d.html"><span class="tagM" title="T3D: GPLs">T3D</span></a> <a href="../tag/t3e.html"><span class="tagM" title="T3E: Ontologies">T3E</span></a> <a href="../tag/t3f.html"><span class="tagM" title="T3F: API">T3F</span></a> <a href="../tag/t4a.html"><span class="tagM" title="T4A: Workbenches">T4A</span></a> <a href="../tag/t4b.html"><span class="tagM" title="T4B: Horizontal Transformation">T4B</span></a> <a href="../tag/t4c.html"><span class="tagM" title="T4C: Vertical Transformation">T4C</span></a> <a href="../tag/t4e.html"><span class="tagM" title="T4E: Simulation">T4E</span></a> <a href="../tag/t4f.html"><span class="tagM" title="T4F: Visualisation">T4F</span></a> <a href="../tag/t5a.html"><span class="tagM" title="T5A: Requirements">T5A</span></a> <a href="../tag/t5b.html"><span class="tagM" title="T5B: Language Description Analysis">T5B</span></a> <a href="../tag/t5c.html"><span class="tagM" title="T5C: Testing">T5C</span></a> <a href="../tag/t5d.html"><span class="tagM" title="T5D: Formal Methods">T5D</span></a> <a href="../tag/t5e.html"><span class="tagM" title="T5E: Empirical Evaluation">T5E</span></a> <a href="../tag/t5h.html"><span class="tagM" title="T5H: Usability">T5H</span></a> <a href="../tag/t6a.html"><span class="tagM" title="T6A: Experience Reports">T6A</span></a> <a href="../tag/t6b.html"><span class="tagM" title="T6B: Industrial">T6B</span></a> <a href="../tag/t6d.html"><span class="tagM" title="T6D: Synergies">T6D</span></a> </li></ul></li>
<li>Tags received: <ul><li><a href="../tag/t1a.html"><span class="tagM" title="T1A: Design">T1A</span></a> <a href="../tag/t1b.html"><span class="tagM" title="T1B: Static Semantics">T1B</span></a> <a href="../tag/t1c.html"><span class="tagM" title="T1C: Behavioural Semantics">T1C</span></a> <a href="../tag/t1d.html"><span class="tagL" title="T1D: Composition">T1D</span></a> <a href="../tag/t1e.html"><span class="tagL" title="T1E: Reuse">T1E</span></a> <a href="../tag/t2b.html"><span class="tagM" title="T2B: Evolution">T2B</span></a> <a href="../tag/t2c.html"><span class="tagM" title="T2C: Variability">T2C</span></a> <a href="../tag/t3a.html"><span class="tagM" title="T3A: Meta-languages">T3A</span></a> <a href="../tag/t3b.html"><span class="tagL" title="T3B: Transformation Languages">T3B</span></a> <a href="../tag/t3c.html"><span class="tagM" title="T3C: DSLs">T3C</span></a> <a href="../tag/t3e.html"><span class="tagM" title="T3E: Ontologies">T3E</span></a> <a href="../tag/t4a.html"><span class="tagM" title="T4A: Workbenches">T4A</span></a> <a href="../tag/t4b.html"><span class="tagM" title="T4B: Horizontal Transformation">T4B</span></a> <a href="../tag/t4c.html"><span class="tagM" title="T4C: Vertical Transformation">T4C</span></a> <a href="../tag/t4d.html"><span class="tagL" title="T4D: Interpretation">T4D</span></a> <a href="../tag/t4e.html"><span class="tagL" title="T4E: Simulation">T4E</span></a> <a href="../tag/t4f.html"><span class="tagL" title="T4F: Visualisation">T4F</span></a> <a href="../tag/t5b.html"><span class="tagM" title="T5B: Language Description Analysis">T5B</span></a> <a href="../tag/t5d.html"><span class="tagM" title="T5D: Formal Methods">T5D</span></a> <a href="../tag/t5e.html"><span class="tagL" title="T5E: Empirical Evaluation">T5E</span></a> <a href="../tag/t5h.html"><span class="tagL" title="T5H: Usability">T5H</span></a> <a href="../tag/t6b.html"><span class="tagL" title="T6B: Industrial">T6B</span></a> <a href="../tag/t6d.html"><span class="tagL" title="T6D: Synergies">T6D</span></a> </li></ul></li>
			</ul>
<h2 id="cfp">Call for Papers (<a href="http://www.sleconf.org/2013/Call_for_Papers.html">source</a>, 88 taggings)</h2>
<p>
</p>
<p>The 6th International Conference on Software Language Engineering (SLE) is devoted to topics related to artificial languages in software engineering. SLE’s mission is to encourage and organize communication among communities that have traditionally looked at software languages from different and yet complementary perspectives. Of particular relevance to SLE are technologies, methods, <span class="term">experiments</span><span class="tag" title="T5E: Empirical Evaluation"><a href="../tag/t5e.html">T5E</a></span>, and <span class="term">case studies</span><span class="tag" title="T6A: Experience Reports"><a href="../tag/t6a.html">T6A</a></span> on software languages from researchers and practitioners who use modeling, grammar, or <span class="term">ontology-based</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span> approaches. <span class="term">Research that bridges, connects and integrates</span><span class="tag" title="T6D: Synergies"><a href="../tag/t6d.html">T6D</a></span> such approaches is particularly welcome.
</p>
<p>
</p>
<h3>Scope</h3>
<p>
</p>
<p>The term “software language” refers to artificial languages used in software development. These include <span class="term">general-purpose programming languages</span><span class="tag" title="T3D: GPLs"><a href="../tag/t3d.html">T3D</a></span>, <span class="term">domain-specific languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span>, modeling and <span class="term">metamodeling languages</span><span class="tag" title="T3A: Meta-languages"><a href="../tag/t3a.html">T3A</a></span>, data models and <span class="term">ontologies</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span>. Examples include <span class="term">general purpose modeling languages</span><span class="tag" title="T3D: GPLs"><a href="../tag/t3d.html">T3D</a></span> such as SysML and UML, metamodeling frameworks such as Ecore, MOF or GOPRR, <span class="term">domain-specific modeling languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span> for business process modeling, such as BPMN, or embedded systems, such as <span class="term">Simulink</span><span class="tag" title="T4E: Simulation"><a href="../tag/t4e.html">T4E</a></span> or Modelica, and specialized XML-based and OWL-based languages and vocabularies. The term “software language” is intentionally broad; besides the above categories and examples, it also encompasses implicit approaches to language definition, such as <span class="term">APIs</span><span class="tag" title="T3F: API"><a href="../tag/t3f.html">T3F</a></span> and collections of design patterns.
</p>
<p>
</p>
<p>Software language engineering is the application of systematic, disciplined, and measurable approaches to the development (<span class="term">design</span><span class="tag" title="T1A: Design"><a href="../tag/t1a.html">T1A</a></span>, implementation, <span class="term">testing</span><span class="tag" title="T5C: Testing"><a href="../tag/t5c.html">T5C</a></span>, <span class="term">deployment</span><span class="tag" title="T2D: Deployment"><a href="../tag/t2d.html">T2D</a></span>), use, <span class="term">deployment</span><span class="tag" title="T2D: Deployment"><a href="../tag/t2d.html">T2D</a></span>, and <span class="term">maintenance</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span> (<span class="term">evolution</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>, <span class="term">recovery</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span>, and <span class="term">retirement</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span>) of these languages. Of special interest are (1) <span class="term">formal descriptions of languages</span><span class="tag" title="T3A: Meta-languages"><a href="../tag/t3a.html">T3A</a></span> that are used to <span class="term">design</span><span class="tag" title="T1A: Design"><a href="../tag/t1a.html">T1A</a></span> or <span class="term">generate</span><span class="tag" title="T4C: Vertical Transformation"><a href="../tag/t4c.html">T4C</a></span> language-based tools and (2) methods and tools for <span class="term">managing such descriptions</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>, including <span class="term">modularization</span><span class="tag" title="T1D: Composition"><a href="../tag/t1d.html">T1D</a></span>, <span class="term">refactoring</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, refinement, <span class="term">composition</span><span class="tag" title="T1D: Composition"><a href="../tag/t1d.html">T1D</a></span>, <span class="term">versioning</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>, <span class="term">co-evolution</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>, <span class="term">recovery</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span>, and analysis.
</p>
<p>
</p>
<h3>Topics of Interest</h3>
<p>
</p>
<p>We solicit high-quality contributions in the area of SLE ranging from theoretical and conceptual contributions to tools, techniques, and frameworks that support the aforementioned <span class="term">lifecycle</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span> activities. The topics of interest include, but are not limited to the following:
</p>
<p>
</p>
<ul>
<li><span class="term">Formalisms used in designing and specifying languages</span><span class="tag" title="T3A: Meta-languages"><a href="../tag/t3a.html">T3A</a></span>, and tools that <span class="term">analyze language descriptions</span><span class="tag" title="T5B: Language Description Analysis"><a href="../tag/t5b.html">T5B</a></span></li>
<li><span class="term">Language implementation techniques</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span>: <span class="term">compiler generator tools</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span>, <span class="term">attribute grammar systems</span><span class="tag" title="T3A: Meta-languages"><a href="../tag/t3a.html">T3A</a></span>, <span class="term">term-rewriting systems</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, functional programming-based combinator libraries; metamodel-based and <span class="term">ontology</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span> tools implementing constraint, rule, view, <span class="term">transformation</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, and query <span class="term">formalisms</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span> and engines.</li>
<li><span class="term">Transformations</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span> and <span class="term">transformation languages</span><span class="tag" title="T3B: Transformation Languages"><a href="../tag/t3b.html">T3B</a></span>, as well as <span class="term">program and model transformation tools</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, and approaches for <span class="term">mapping</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span> between <span class="term">ontologies</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span>.</li>
<li><span class="term">Language evolution</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>: Included are <span class="term">extensible languages</span><span class="tag" title="T1D: Composition"><a href="../tag/t1d.html">T1D</a></span> and <span class="term">type systems</span><span class="tag" title="T1B: Static Semantics"><a href="../tag/t1b.html">T1B</a></span> and their supporting tools and <span class="term">language conversion tools</span><span class="tag" title="T4B: Horizontal Transformation"><a href="../tag/t4b.html">T4B</a></span>, approaches for <span class="term">ontology</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span> <span class="term">evolution</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>, approaches for impact analysis of <span class="term">language evolution</span><span class="tag" title="T2B: Evolution"><a href="../tag/t2b.html">T2B</a></span>.</li>
<li>Approaches to the <span class="term">elicitation</span><span class="tag" title="T5A: Requirements"><a href="../tag/t5a.html">T5A</a></span>, <span class="term">specification</span><span class="tag" title="T5A: Requirements"><a href="../tag/t5a.html">T5A</a></span>, and <span class="term">verification</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span> of <span class="term">requirements for software languages</span><span class="tag" title="T5A: Requirements"><a href="../tag/t5a.html">T5A</a></span>: Examples include the use of <span class="term">requirements engineering</span><span class="tag" title="T5A: Requirements"><a href="../tag/t5a.html">T5A</a></span> techniques in domain engineering and in the development of <span class="term">domain-specific languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span> and the application of <span class="term">logic-based formalisms</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span> for <span class="term">verifying</span><span class="tag" title="T5D: Formal Methods"><a href="../tag/t5d.html">T5D</a></span> <span class="term">language and domain requirements</span><span class="tag" title="T5A: Requirements"><a href="../tag/t5a.html">T5A</a></span>.</li>
<li><span class="term">Language development frameworks</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span>, methodologies, techniques, best practices, and tools for the broader language <span class="term">lifecycle</span><span class="tag" title="T2A: Lifecycle"><a href="../tag/t2a.html">T2A</a></span> covering phases such as analysis, <span class="term">testing</span><span class="tag" title="T5C: Testing"><a href="../tag/t5c.html">T5C</a></span>, and <span class="term">documentation</span><span class="tag" title="T2E: Documentation"><a href="../tag/t2e.html">T2E</a></span>. For example, frameworks for <span class="term">advanced type or reasoning systems</span><span class="tag" title="T1B: Static Semantics"><a href="../tag/t1b.html">T1B</a></span>, constraint mechanisms, tools for metrics collection and language usage analysis, assessing language <span class="term">usability</span><span class="tag" title="T5H: Usability"><a href="../tag/t5h.html">T5H</a></span>, <span class="term">documentation</span><span class="tag" title="T2E: Documentation"><a href="../tag/t2e.html">T2E</a></span> <span class="term">generators</span><span class="tag" title="T4C: Vertical Transformation"><a href="../tag/t4c.html">T4C</a></span>, <span class="term">visualization backends</span><span class="tag" title="T4F: Visualisation"><a href="../tag/t4f.html">T4F</a></span>, <span class="term">generation</span><span class="tag" title="T4C: Vertical Transformation"><a href="../tag/t4c.html">T4C</a></span> of <span class="term">tests</span><span class="tag" title="T5C: Testing"><a href="../tag/t5c.html">T5C</a></span> for language-based tools, knowledge and process management approaches, as well as <span class="term">IDE support</span><span class="tag" title="T4A: Workbenches"><a href="../tag/t4a.html">T4A</a></span> for many of these activities are of interest.</li>
<li><span class="term">Integration and interoperation between different approaches to software language engineering</span><span class="tag" title="T6D: Synergies"><a href="../tag/t6d.html">T6D</a></span>; for example, ways to integrate grammar-based and <span class="term">ontology-based</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span> approaches to language definition.</li>
<li><span class="term">Design challenges</span><span class="tag" title="T1A: Design"><a href="../tag/t1a.html">T1A</a></span> in SLE: Example challenges include finding a balance between specificity and generality in designing <span class="term">domain-specific languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span>, between <span class="term">strong static typing and weaker yet more flexible type systems</span><span class="tag" title="T1B: Static Semantics"><a href="../tag/t1b.html">T1B</a></span>, or between <span class="term">deep and shallow embedding</span><span class="tag" title="T1D: Composition"><a href="../tag/t1d.html">T1D</a></span> approaches, as, for example, in the context of adding type-safe XML and database programming support to <span class="term">general-purpose programming languages</span><span class="tag" title="T3D: GPLs"><a href="../tag/t3d.html">T3D</a></span>.</li>
<li>Applications of languages including innovative <span class="term">domain-specific languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span> or <span class="term">“little” languages</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span>: Examples include policy languages for security or service-oriented architectures, web-engineering with <span class="term">schema-based generators</span><span class="tag" title="T4C: Vertical Transformation"><a href="../tag/t4c.html">T4C</a></span> or <span class="term">ontology-based annotations</span><span class="tag" title="T3E: Ontologies"><a href="../tag/t3e.html">T3E</a></span>. Of specific interest are the engineering aspects of <span class="term">domain-specific language</span><span class="tag" title="T3C: DSLs"><a href="../tag/t3c.html">T3C</a></span> support in all of these cases.</li>
</ul>
<p>
</p>
<p>The program committee chairs encourage potential contributors to contact them with questions about the scope and topics of interest of SLE. The overall principle of SLE is to be broad-minded and inclusive about relevance and scope, and to invest in community building when soliciting and selecting papers.
</p>
<p>
</p>
<h3>Types of Submissions</h3>
<p>
</p>
<p>We solicit the following types of papers:
</p>
<p>
</p>
<ul>
<li>Research papers: These should report a substantial research contribution to SLE or successful application of SLE techniques or both. Full paper submissions must not exceed 20 pages (in LNCS format).</li>
<li><span class="term">Industrial</span><span class="tag" title="T6B: Industrial"><a href="../tag/t6b.html">T6B</a></span> <span class="term">experience papers</span><span class="tag" title="T6A: Experience Reports"><a href="../tag/t6a.html">T6A</a></span>: These papers discuss <span class="term">practical applications</span><span class="tag" title="T6B: Industrial"><a href="../tag/t6b.html">T6B</a></span> of SLE technology with an emphasis on the advantages and disadvantages of the method, techniques, or tools used. These papers must not exceed 10 pages (in LNCS format).</li>
<li>Tool demonstration papers: Because of SLE’s ample interest in tools, we seek papers that present software tools related to the field of SLE. These papers will accompany a tool demonstration to be given at the conference. These papers must not exceed 10 pages (in LNCS format). The selection criteria include the originality of the tool, its innovative aspects, the relevance of the tool to SLE, and the maturity of the tool.</li>
</ul><h2 id="lop">List of Papers (1+19+2, <a href="https://dblp.org/db/conf/sle/sle2013.html">source</a>)</h2>
<ul class="lop">

<li><span title="Keynote">🔥</span> <em><a href="keynote1.html">Dark Knowledge and Graph Grammars in Automated Software Design</a></em> (<a href="../profile/DonSBatory.html">Don S. Batory</a>, <a href="../profile/RuiCarlosGonçalves.html">Rui Carlos Gonçalves</a>, <a href="../profile/BryanMarker.html">Bryan Marker</a>, <a href="../profile/JanetSiegmund.html">Janet Siegmund</a>) 
<ul><li>
<a href="../tag/t4c.html"><span class="tagM" title="The keynote frames automated software design as stepwise program derivation using (graph-grammar) transformation chains, i.e., refinement/generative engineering.">T4C: Vertical Transformation</span></a>
<a href="../tag/t3b.html"><span class="tagL" title="Graph-grammar rewrite rules are used as the main transformation formalism for deriving implementations from designs.">T3B: Transformation Languages</span></a>
<a href="../tag/t1a.html"><span class="tagL" title="It explicitly links the approach to language design/engineering, treating “design spaces” as languages with structured sentences.">T1A: Design</span></a>
</li></ul></li>
<li><em><a href="paper01.html">Developing a Domain-Specific Language for Scheduling in the European Energy Sector</a></em> (<a href="../profile/StefanSobernig.html">Stefan Sobernig</a>, <a href="../profile/MarkStrembeck.html">Mark Strembeck</a>, <a href="../profile/AndreasJBeck.html">Andreas J. Beck</a>) 
<ul><li>
<a href="../tag/t3c.html"><span class="tagM" title="The central contribution is the design and implementation of a domain-specific language for expressing electricity trading schedules.">T3C: DSLs</span></a>
<a href="../tag/t4b.html"><span class="tagL" title="A key motivation is to cope with multiple proprietary/standard schedule formats, which calls for mapping/conversion across representations.">T4B: Horizontal Transformation</span></a>
<a href="../tag/t6b.html"><span class="tagL" title="The work is grounded in an industrial domain (European energy trading) and reports on a real development project.">T6B: Industrial</span></a>
</li></ul></li>
<li><em><a href="paper02.html">Micro-Machinations: A DSL for Game Economies</a></em> (<a href="../profile/PaulKlint.html">Paul Klint</a>, <a href="../profile/RiemervanRozen.html">Riemer van Rozen</a>) 
<ul><li>
<a href="../tag/t3c.html"><span class="tagM" title="The paper proposes a dedicated DSL to let game designers specify and communicate game-economy mechanics.">T3C: DSLs</span></a>
<a href="../tag/t4e.html"><span class="tagL" title="The DSL targets the modeling and (typically) simulation/analysis of game economies to understand emergent behavior.">T4E: Simulation</span></a>
<a href="../tag/t5h.html"><span class="tagL" title="A stated goal is improving designer productivity and designer–engineer communication, i.e., human-centered usability concerns.">T5H: Usability</span></a>
</li></ul></li>
<li><em><a href="paper03.html">xMOF: Executable DSMLs Based on fUML</a></em> (<a href="../profile/TanjaMayerhofer.html">Tanja Mayerhofer</a>, <a href="../profile/PhilipLanger.html">Philip Langer</a>, <a href="../profile/ManuelWimmer.html">Manuel Wimmer</a>, <a href="../profile/GertiKappel.html">Gerti Kappel</a>) 
<ul><li>
<a href="../tag/t1c.html"><span class="tagM" title="The main focus is defining and supporting behavioral/executable semantics for DSMLs by building on fUML.">T1C: Behavioural Semantics</span></a>
<a href="../tag/t4d.html"><span class="tagL" title="It aims at executing models (incl. debugging/simulation support), i.e., interpretation/runtime facilities for DSMLs.">T4D: Interpretation</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="The contribution targets domain-specific modeling languages and how to make them executable.">T3C: DSLs</span></a>
</li></ul></li>
<li><em><a href="paper04.html">Variability Support in Domain-Specific Language Development</a></em> (<a href="../profile/EdoardoVacchi.html">Edoardo Vacchi</a>, <a href="../profile/WalterCazzola.html">Walter Cazzola</a>, <a href="../profile/SureshPillay.html">Suresh Pillay</a>, <a href="../profile/BenoîtCombemale.html">Benoît Combemale</a>) 
<ul><li>
<a href="../tag/t2c.html"><span class="tagM" title="The paper’s core problem is handling variability across families of related DSLs to reduce repeated language/tool engineering effort.">T2C: Variability</span></a>
<a href="../tag/t1d.html"><span class="tagL" title="It leverages modularization/composition mechanisms to factor commonality and manage variation points in DSL implementations.">T1D: Composition</span></a>
<a href="../tag/t1e.html"><span class="tagL" title="The approach is motivated by reuse of language concepts and reusable tool support across multiple DSL variants.">T1E: Reuse</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="The setting is recurring DSL development, i.e., engineering multiple DSLs in a domain or product family.">T3C: DSLs</span></a>
</li></ul></li>
<li><em><a href="paper05.html">Software Evolution to Domain-Specific Languages</a></em> (<a href="../profile/StefanFehrenbach.html">Stefan Fehrenbach</a>, <a href="../profile/SebastianErdweg.html">Sebastian Erdweg</a>, <a href="../profile/KlausOstermann.html">Klaus Ostermann</a>) 
<ul><li>
<a href="../tag/t2b.html"><span class="tagM" title="The contribution proposes a process for evolving existing systems toward (embedded) DSL usage rather than rewriting from scratch.">T2B: Evolution</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="The target outcome is adoption of embedded domain-specific languages to improve maintainability and tool support.">T3C: DSLs</span></a>
<a href="../tag/t3b.html"><span class="tagL" title="The proposed evolution process relies on systematic program changes/refactorings that can be viewed as transformation steps toward DSL usage.">T3B: Transformation Languages</span></a>
</li></ul></li>
<li><em><a href="paper06.html">Micropatterns in Grammars</a></em> (<a href="../profile/VadimZaytsev.html">Vadim Zaytsev</a>) 
<ul><li>
<a href="../tag/t5b.html"><span class="tagM" title="The paper introduces and studies “micropatterns” to analyze and comprehend grammar-like language descriptions (parsers, metamodels, data models).">T5B: Language Description Analysis</span></a>
<a href="../tag/t3a.html"><span class="tagL" title="It treats grammars and related schema formalisms as meta-languages whose structure can be characterized and compared.">T3A: Meta-languages</span></a>
<a href="../tag/t2b.html"><span class="tagL" title="Identifying recurring structural fragments supports grammar comprehension and can inform maintenance/evolution of grammarware artifacts.">T2B: Evolution</span></a>
</li></ul></li>
<li><em><a href="paper07.html">Safe Specification of Operator Precedence Rules</a></em> (<a href="../profile/AliAfroozeh.html">Ali Afroozeh</a>, <a href="../profile/MarkvandenBrand.html">Mark van den Brand</a>, <a href="../profile/AdrianJohnstone.html">Adrian Johnstone</a>, <a href="../profile/ElizabethScott.html">Elizabeth Scott</a>, <a href="../profile/JurgenVinju.html">Jurgen Vinju</a>) 
<ul><li>
<a href="../tag/t1a.html"><span class="tagM" title="The central goal is improving concrete-syntax design by specifying operator precedence declaratively and safely.">T1A: Design</span></a>
<a href="../tag/t3a.html"><span class="tagL" title="The work is about constructs for grammar specification and disambiguation—i.e., a meta-language for defining syntax and precedence.">T3A: Meta-languages</span></a>
<a href="../tag/t3b.html"><span class="tagL" title="The implementation relies on systematic grammar rewriting, i.e., transforming specifications to obtain a correct parser.">T3B: Transformation Languages</span></a>
</li></ul></li>
<li><em><a href="paper08.html">Detecting Ambiguity in Programming Language Grammars</a></em> (<a href="../profile/NaveneethaVasudevan.html">Naveneetha Vasudevan</a>, <a href="../profile/LaurenceTratt.html">Laurence Tratt</a>) 
<ul><li>
<a href="../tag/t5b.html"><span class="tagM" title="The main contribution is an analysis technique for detecting ambiguity in context-free grammars for programming languages.">T5B: Language Description Analysis</span></a>
<a href="../tag/t5e.html"><span class="tagL" title="The paper emphasizes evaluation via generated/random grammars (Boltzmann sampling, mutation) to test ambiguity-detection techniques at scale.">T5E: Empirical Evaluation</span></a>
<a href="../tag/t3a.html"><span class="tagL" title="Grammars are the analyzed artifacts, and the techniques operate at the level of grammar specifications.">T3A: Meta-languages</span></a>
</li></ul></li>
<li><em><a href="paper09.html">A Pretty Good Formatting Pipeline</a></em> (<a href="../profile/AnyaHeleneBagge.html">Anya Helene Bagge</a>, <a href="../profile/TeroHasu.html">Tero Hasu</a>) 
<ul><li>
<a href="../tag/t4b.html"><span class="tagM" title="The paper presents a pluggable pipeline for transforming internal program representations (e.g., ASTs) into formatted text.">T4B: Horizontal Transformation</span></a>
<a href="../tag/t4a.html"><span class="tagL" title="The contribution is packaged as a reusable library/framework that can be integrated into transformation and generation tooling.">T4A: Workbenches</span></a>
<a href="../tag/t5h.html"><span class="tagL" title="It is motivated by human-facing code readability and comprehension, treating formatting as a usability concern for developers.">T5H: Usability</span></a>
</li></ul></li>
<li><em><a href="paper10.html">The State of the Art in Language Workbenches: Conclusions from the Language Workbench Challenge</a></em> (<a href="../profile/SebastianErdweg.html">Sebastian Erdweg</a>, <a href="../profile/TijsvanderStorm.html">Tijs van der Storm</a>, <a href="../profile/MarkusVölter.html">Markus Völter</a>, <a href="../profile/MeinteBoersma.html">Meinte Boersma</a>, <a href="../profile/RemiBosman.html">Remi Bosman</a>, <a href="../profile/WilliamRCook.html">William R. Cook</a>, <a href="../profile/AlbertGerritsen.html">Albert Gerritsen</a>, <a href="../profile/AngeloHulshout.html">Angelo Hulshout</a>, <a href="../profile/StevenKelly.html">Steven Kelly</a>, <a href="../profile/AlexLoh.html">Alex Loh</a>, <a href="../profile/GabriëlKonat.html">Gabriël Konat</a>, <a href="../profile/PedroJMolina.html">Pedro J. Molina</a>, <a href="../profile/MartinPalatnik.html">Martin Palatnik</a>, <a href="../profile/RistoPohjonen.html">Risto Pohjonen</a>, <a href="../profile/EugenSchindler.html">Eugen Schindler</a>, <a href="../profile/KlemensSchindler.html">Klemens Schindler</a>, <a href="../profile/RiccardoSolmi.html">Riccardo Solmi</a>, <a href="../profile/VladVergu.html">Vlad Vergu</a>, <a href="../profile/EelcoVisser.html">Eelco Visser</a>, <a href="../profile/KevinvanderVlist.html">Kevin van der Vlist</a>, <a href="../profile/GuidoWachsmuth.html">Guido Wachsmuth</a>, <a href="../profile/JimivanderWoning.html">Jimi van der Woning</a>) 
<ul><li>
<a href="../tag/t4a.html"><span class="tagM" title="The paper’s primary focus is language workbenches—their capabilities, trade-offs, and tool support for implementing languages.">T4A: Workbenches</span></a>
<a href="../tag/t5e.html"><span class="tagL" title="It synthesizes evidence from repeated challenge tasks used to compare workbenches, providing an empirical/comparative perspective.">T5E: Empirical Evaluation</span></a>
<a href="../tag/t6d.html"><span class="tagL" title="The Language Workbench Challenge explicitly creates a cross-tool community forum, emphasizing synergies and shared evaluation criteria.">T6D: Synergies</span></a>
</li></ul></li>
<li><em><a href="paper11.html">A Model-Driven Approach to Enhance Tool Interoperability Using the Theory of Models of Computation</a></em> (<a href="../profile/PapaIssaDiallo.html">Papa Issa Diallo</a>, <a href="../profile/JoëlChampeau.html">Joël Champeau</a>, <a href="../profile/LoïcLagadec.html">Loïc Lagadec</a>) 
<ul><li>
<a href="../tag/t4b.html"><span class="tagM" title="The core problem is interoperability across heterogeneous tools, addressed through explicit mappings/exchanges between executable models.">T4B: Horizontal Transformation</span></a>
<a href="../tag/t5d.html"><span class="tagL" title="It leverages formal “models of computation” to reason about and constrain executable model exchanges in a principled way.">T5D: Formal Methods</span></a>
<a href="../tag/t1d.html"><span class="tagL" title="The paper is fundamentally about coordinating and integrating heterogeneous tool chains and execution models.">T1D: Composition</span></a>
</li></ul></li>
<li><em><a href="paper12.html">Whiley: A Platform for Research in Software Verification</a></em> (<a href="../profile/DavidJPearce.html">David J. Pearce</a>, <a href="../profile/LindsayGroves.html">Lindsay Groves</a>) 
<ul><li>
<a href="../tag/t5d.html"><span class="tagM" title="The paper introduces a language/platform explicitly designed to support program verification and elimination of runtime errors (formal methods focus).">T5D: Formal Methods</span></a>
<a href="../tag/t1a.html"><span class="tagL" title="Whiley is a purpose-built programming language whose design is shaped by verification goals and specification support.">T1A: Design</span></a>
<a href="../tag/t1b.html"><span class="tagL" title="Verification-oriented languages typically rely on rich static semantics (e.g., checked properties, contracts, or type-like reasoning) to enable automated checking.">T1B: Static Semantics</span></a>
</li></ul></li>
<li><em><a href="paper13.html">Method and Tool Support for Classifying Software Languages with Wikipedia</a></em> (<a href="../profile/RalfLämmel.html">Ralf Lämmel</a>, <a href="../profile/DominikMosen.html">Dominik Mosen</a>, <a href="../profile/AndreiVaranovich.html">Andrei Varanovich</a>) 
<ul><li>
<a href="../tag/t3e.html"><span class="tagM" title="The main contribution is a method/tool for building a classification (taxonomy/ontology-like structure) of software languages using Wikipedia categories.">T3E: Ontologies</span></a>
<a href="../tag/t4f.html"><span class="tagL" title="The tool visualizes the extracted Wikipedia category graph in a navigable, tree-like form to support exploration and understanding.">T4F: Visualisation</span></a>
<a href="../tag/t5b.html"><span class="tagL" title="It performs analysis/mining over a large knowledge base (Wikipedia) to derive and refine language-classification structures.">T5B: Language Description Analysis</span></a>
</li></ul></li>
<li><em><a href="paper14.html">A Language Independent Task Engine for Incremental Name and Type Analysis</a></em> (<a href="../profile/GuidoWachsmuth.html">Guido Wachsmuth</a>, <a href="../profile/GabriëlKonat.html">Gabriël Konat</a>, <a href="../profile/VladVergu.html">Vlad Vergu</a>, <a href="../profile/DannyMGroenewegen.html">Danny M. Groenewegen</a>, <a href="../profile/EelcoVisser.html">Eelco Visser</a>) 
<ul><li>
<a href="../tag/t1b.html"><span class="tagM" title="The primary contribution is incremental name and type analysis—core static-semantics infrastructure for IDE feedback.">T1B: Static Semantics</span></a>
<a href="../tag/t4a.html"><span class="tagL" title="It provides method/tool support (a task engine) intended to be embedded in IDEs to deliver responsive analysis.">T4A: Workbenches</span></a>
<a href="../tag/t1d.html"><span class="tagL" title="The approach factors analysis into modular tasks with dependencies, emphasizing compositional structuring of analyses across languages.">T1D: Composition</span></a>
</li></ul></li>
<li><em><a href="paper15.html">A Generic Framework for Symbolic Execution</a></em> (<a href="../profile/AndreiArusoaie.html">Andrei Arusoaie</a>, <a href="../profile/DorelLucanu.html">Dorel Lucanu</a>, <a href="../profile/VladRusu.html">Vlad Rusu</a>) 
<ul><li>
<a href="../tag/t5d.html"><span class="tagM" title="Symbolic execution is a formal-methods technique, and the paper presents a generic, semantics-based symbolic execution framework.">T5D: Formal Methods</span></a>
<a href="../tag/t1c.html"><span class="tagL" title="The framework assumes a formal operational semantics (term rewriting) and systematically extends it to enable symbolic execution.">T1C: Behavioural Semantics</span></a>
<a href="../tag/t4c.html"><span class="tagL" title="It automatically generates a derived (symbolic) language definition from an original semantics, i.e., a generative refinement of semantics artifacts.">T4C: Vertical Transformation</span></a>
</li></ul></li>
<li><em><a href="paper16.html">Circular Higher-Order Reference Attribute Grammars</a></em> (<a href="../profile/EmmaSöderberg.html">Emma Söderberg</a>, <a href="../profile/GörelHedin.html">Görel Hedin</a>) 
<ul><li>
<a href="../tag/t3a.html"><span class="tagM" title="The paper advances attribute-grammar technology (higher-order RAGs with circularity/rewrites), i.e., a core meta-language for language implementation.">T3A: Meta-languages</span></a>
<a href="../tag/t5b.html"><span class="tagL" title="A central concern is well-defined evaluation in the presence of interacting features (circularity and rewrites), i.e., analysis of language-definition behavior.">T5B: Language Description Analysis</span></a>
<a href="../tag/t1d.html"><span class="tagL" title="It studies how declarative rewrites and circular attributes interact, touching on compositional coordination between specification mechanisms.">T1D: Composition</span></a>
</li></ul></li>
<li><em><a href="paper17.html">Mapping-Aware Megamodeling: Design Patterns and Laws</a></em> (<a href="../profile/ZinovyDiskin.html">Zinovy Diskin</a>, <a href="../profile/SaharKokaly.html">Sahar Kokaly</a>, <a href="../profile/TomMaibaum.html">Tom Maibaum</a>) 
<ul><li>
<a href="../tag/t3a.html"><span class="tagM" title="Megamodels act as meta-level descriptions of models and mappings; the paper proposes richer, mapping-aware megamodeling constructs and principles.">T3A: Meta-languages</span></a>
<a href="../tag/t4b.html"><span class="tagL" title="The work centers on explicit mappings between models (transformations/conversions) and how they are represented and reasoned about.">T4B: Horizontal Transformation</span></a>
<a href="../tag/t5d.html"><span class="tagL" title="It formulates “laws” and design patterns for megamodels, emphasizing principled (often formal) constraints on mapping structures and operations.">T5D: Formal Methods</span></a>
</li></ul></li>
<li><em><a href="paper18.html">Partial Instances via Subclassing</a></em> (<a href="../profile/KacperBąk.html">Kacper Bąk</a>, <a href="../profile/ZinovyDiskin.html">Zinovy Diskin</a>, <a href="../profile/MichałAntkiewicz.html">Michał Antkiewicz</a>, <a href="../profile/KrzysztofCzarnecki.html">Krzysztof Czarnecki</a>, <a href="../profile/AndrzejWąsowski.html">Andrzej Wąsowski</a>) 
<ul><li>
<a href="../tag/t1a.html"><span class="tagM" title="The main contribution is a language-design extension to object-oriented modeling instantiation, introducing partial/uncertain instances via subclassing.">T1A: Design</span></a>
<a href="../tag/t5d.html"><span class="tagL" title="It provides a formal account of partial instantiation (e.g., completions, open-world assumptions) to ensure the notion is well-defined.">T5D: Formal Methods</span></a>
<a href="../tag/t3a.html"><span class="tagL" title="The work operates at the metamodeling/meta-level of class-diagram instance semantics, i.e., reasoning about a modeling formalism itself.">T3A: Meta-languages</span></a>
</li></ul></li>
<li><em><a href="paper19.html">Reifying Concurrency for Executable Metamodeling</a></em> (<a href="../profile/BenoîtCombemale.html">Benoît Combemale</a>, <a href="../profile/JulienDeAntoni.html">Julien De Antoni</a>, <a href="../profile/MatiasVaraLarsen.html">Matias Vara Larsen</a>, <a href="../profile/FrédéricMallet.html">Frédéric Mallet</a>, <a href="../profile/OlivierBarais.html">Olivier Barais</a>, <a href="../profile/BenoîtBaudry.html">Benoît Baudry</a>, <a href="../profile/RobertBFrance.html">Robert B. France</a>) 
<ul><li>
<a href="../tag/t1c.html"><span class="tagM" title="The central focus is making concurrency semantics explicit in executable metamodeling for DSMLs (behavioral semantics of concurrent behavior).">T1C: Behavioural Semantics</span></a>
<a href="../tag/t4d.html"><span class="tagL" title="It addresses how executable metamodels run in an execution environment, emphasizing runtime/interpretation concerns for concurrent DSMLs.">T4D: Interpretation</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="The contribution targets DSML engineering, especially for DSMLs whose semantics depend on concurrency models.">T3C: DSLs</span></a>
</li></ul></li>
<li><span title="Poster">🖼️</span> <em><a href="poster1.html">Guided Grammar Convergence</a></em> (<a href="../profile/VadimZaytsev.html">Vadim Zaytsev</a>) 
<ul><li>
<a href="../tag/t5b.html"><span class="tagM" title="The main contribution is analysis and reconciliation of language descriptions (grammars) via milestones of identity/equivalence and structural matching.">T5B: Language Description Analysis</span></a>
<a href="../tag/t4b.html"><span class="tagL" title="It aims to infer (bidirectional) transformation steps between different grammar representations, i.e., mappings/conversions across formalisms.">T4B: Horizontal Transformation</span></a>
<a href="../tag/t3a.html"><span class="tagL" title="The entire setting is about meta-languages for syntax/grammar specification (grammars “in a broad sense”), including normalization to a normal form.">T3A: Meta-languages</span></a>
<a href="../tag/t3b.html"><span class="tagL" title="Conventional and guided convergence are explicitly framed as sequences of grammar transformation steps (including automatically inferred ones).">T3B: Transformation Languages</span></a>
</li></ul></li>
<li><span title="Poster">🖼️</span> <em><a href="poster2.html">Towards Controlling Refinements of Statecharts</a></em> (<a href="../profile/ConnerHansen.html">Conner Hansen</a>, <a href="../profile/EugeneSyriani.html">Eugene Syriani</a>, <a href="../profile/LeviLúcio.html">Levi Lúcio</a>) 
<ul><li>
<a href="../tag/t2b.html"><span class="tagM" title="The paper’s core problem is controlling incremental refinement across versions of a Statecharts model to support predictable evolution and maintenance.">T2B: Evolution</span></a>
<a href="../tag/t5d.html"><span class="tagL" title="It defines a formal refinement relation and constraints (e.g., inclusion conditions over events/guards/structure) to guarantee behaviour preservation.">T5D: Formal Methods</span></a>
<a href="../tag/t4c.html"><span class="tagL" title="“Refinement” is treated as a disciplined stepwise development relation (additive, structure-preserving), i.e., a vertical refinement discipline over models.">T4C: Vertical Transformation</span></a>
<a href="../tag/t3c.html"><span class="tagL" title="Statecharts are treated as a domain-specific modeling language whose refinement rules constrain how models can be extended.">T3C: DSLs</span></a>
</li></ul></li></ul><h2 id="org">Organisers</h2><ul>
<li><a href="../profile/EricVanWyk.html">Eric Van Wyk</a> (<a href="https://www.sleconf.org/2013/Committees.html">General Chair</a>)</li>
<li><a href="../profile/MartinErwig.html">Martin Erwig</a> (<a href="https://www.sleconf.org/2013/Committees.html">Programme Chair</a>)</li>
<li><a href="../profile/RichardFPaige.html">Richard F. Paige</a> (<a href="https://www.sleconf.org/2013/Committees.html">Programme Chair</a>)</li>
<li><a href="../profile/JeremyGibbons.html">Jeremy Gibbons</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/EmilieBalland.html">Emilie Balland</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/OlafChitil.html">Olaf Chitil</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/JamesRCordy.html">James R. Cordy</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/DavideDiRuscio.html">Davide Di Ruscio</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/IavorDiatchki.html">Iavor Diatchki</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/AnneEtien.html">Anne Etien</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/JeanMarieFavre.html">Jean-Marie Favre</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/DraganGašević.html">Dragan Gašević</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/AndyGill.html">Andy Gill</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/JeffreyGGray.html">Jeffrey G. Gray</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/GiancarloGuizzardi.html">Giancarlo Guizzardi</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/GörelHedin.html">Görel Hedin</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/MarkusHerrmannsdörfer.html">Markus Herrmannsdörfer</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/ZhenjiangHu.html">Zhenjiang Hu</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/OlegKiselyov.html">Oleg Kiselyov</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/PaulKlint.html">Paul Klint</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/ThomasKühne.html">Thomas Kühne</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/KimMens.html">Kim Mens</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/PierreEtienneMoreau.html">Pierre-Etienne Moreau</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/KlausOstermann.html">Klaus Ostermann</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/ArndPoetzschHeffter.html">Arnd Poetzsch-Heffter</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/FionaPolack.html">Fiona Polack</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/LukasRenggli.html">Lukas Renggli</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/BernhardRumpe.html">Bernhard Rumpe</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/JoãoSaraiva.html">João Saraiva</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/FriedrichSteimann.html">Friedrich Steimann</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/GabrieleTaentzer.html">Gabriele Taentzer</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/MarkvandenBrand.html">Mark van den Brand</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
<li><a href="../profile/JurgenVinju.html">Jurgen Vinju</a> (<a href="https://www.sleconf.org/2013/Committees.html">PC</a>)</li>
</ul>
		<clear/>
		<footer/>
	</body>
</html>
